import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from 'next/font/google'
import "./globals.css";
import { MainNav } from "@/components/navbar";
import { ThemeProvider } from "@/components/theme/theme-provider"
import { cn } from "@/lib/utils";

 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const jakartaFont = Plus_Jakarta_Sans({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={cn(
        "min-h-screen antialiased", jakartaFont.className)}
      >
        <ThemeProvider 
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
      <div className="relative flex min-h-screen min-w-full flex-col">

            <MainNav />
            <div >{children}</div>
        </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
